"""
init

Revision ID: 139ec68b8dd9
Revises: 
Create Date: 2026-05-09 13:54:48.675197

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "139ec68b8dd9"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("links",
    sa.Column("url", sa.String(), nullable=False),
    sa.Column("short_code", sa.String(length=16), nullable=False),
    sa.Column("owner_id", sa.Integer(), nullable=True),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.ForeignKeyConstraint(["owner_id"], ["users.id"], name=op.f("fk_links_owner_id_users")),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    sa.UniqueConstraint("short_code", name=op.f("uq_links_short_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
