"""
Add custom-slug column.

Revision ID: 790ffec2620b
Revises: aefc1d1bcb61
Create Date: 2026-06-04 13:31:09.429792

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '790ffec2620b'
down_revision: str | Sequence[str] | None = 'aefc1d1bcb61'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'links',
        sa.Column('custom_slug', sa.String(length=50), nullable=True),
    )
    op.alter_column(
        'links',
        'slug',
        existing_type=sa.VARCHAR(length=16),
        type_=sa.String(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'links',
        'slug',
        existing_type=sa.VARCHAR(length=50),
        type_=sa.String(length=16),
        nullable=False,
    )
    op.drop_column('links', 'custom_slug')
    # ### end Alembic commands ###
