"""
create links table

Revision ID: 4b7581fad94d
Revises: 579da99acf4c
Create Date: 2026-05-06 19:17:08.231720

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "4b7581fad94d"
down_revision: str | Sequence[str] | None = "579da99acf4c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
