"""
create links table

Revision ID: 579da99acf4c
Revises: 5b0f1223ef6f
Create Date: 2026-05-06 19:06:29.706621

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "579da99acf4c"
down_revision: str | Sequence[str] | None = "5b0f1223ef6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("links",
    sa.Column("original_url", sa.String(), nullable=False),
    sa.Column("short_code", sa.String(), nullable=False),
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    sa.UniqueConstraint("short_code", name=op.f("uq_links_short_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
