"""
create links table

Revision ID: 68d0850afd24
Revises: 821543b8a44c
Create Date: 2026-05-06 19:35:40.389308

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "68d0850afd24"
down_revision: str | Sequence[str] | None = "821543b8a44c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("links",
    sa.Column("original_url", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("short_code", sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column("created_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    sa.UniqueConstraint("short_code", name=op.f("uq_links_short_code"), postgresql_include=[], postgresql_nulls_not_distinct=False),
    )
    # ### end Alembic commands ###
