"""
rename short_code to slug

Revision ID: 337b895f8782
Revises: 139ec68b8dd9
Create Date: 2026-05-13 16:40:14.628474

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '337b895f8782'
down_revision: str | Sequence[str] | None = '139ec68b8dd9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('slug', sa.String(length=16), nullable=False))
    op.drop_constraint(op.f('uq_links_short_code'), 'links', type_='unique')
    op.create_unique_constraint(op.f('uq_links_slug'), 'links', ['slug'])
    op.drop_column('links', 'short_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('links', sa.Column('short_code', sa.VARCHAR(length=16), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('uq_links_slug'), 'links', type_='unique')
    op.create_unique_constraint(op.f('uq_links_short_code'), 'links', ['short_code'], postgresql_nulls_not_distinct=False)
    op.drop_column('links', 'slug')
    # ### end Alembic commands ###
