"""
create links table

Revision ID: 821543b8a44c
Revises: a3ee793b44db
Create Date: 2026-05-06 19:21:21.504804

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "821543b8a44c"
down_revision: str | Sequence[str] | None = "a3ee793b44db"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
