"""
final fix users and links relation

Revision ID: 3ba5ae8d20f2
Revises: 1421b38e35e5
Create Date: 2026-05-08 10:41:36.208946

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3ba5ae8d20f2"
down_revision: str | Sequence[str] | None = "1421b38e35e5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "owner_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "owner_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
