"""
change password_hash type from bytes to str in users table

Revision ID: 0903734d8ba3
Revises: 79631b196fe8
Create Date: 2026-05-14 15:50:57.247467

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0903734d8ba3'
down_revision: str | Sequence[str] | None = '79631b196fe8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
