"""
add users and links relation

Revision ID: aac6212d1510
Revises: af8d9c6c20a0
Create Date: 2026-05-08 10:09:00.634863

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aac6212d1510"
down_revision: str | Sequence[str] | None = "af8d9c6c20a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("users",
    sa.Column("username", sa.String(length=30), nullable=False),
    sa.Column("email", sa.String(length=255), nullable=False),
    sa.Column("role", sa.Enum("admin", "user", name="userrole"), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.add_column("links", sa.Column("owner_id", sa.Integer(), nullable=False))
    op.create_foreign_key(op.f("fk_links_owner_id_users"), "links", "users", ["owner_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_links_owner_id_users"), "links", type_="foreignkey")
    op.drop_column("links", "owner_id")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
