"""
create links table

Revision ID: a3ee793b44db
Revises: 4b7581fad94d
Create Date: 2026-05-06 19:19:42.921223

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "a3ee793b44db"
down_revision: str | Sequence[str] | None = "4b7581fad94d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
