"""
fix users and links relation

Revision ID: 1421b38e35e5
Revises: aac6212d1510
Create Date: 2026-05-08 10:39:12.641110

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1421b38e35e5"
down_revision: str | Sequence[str] | None = "aac6212d1510"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "owner_id",
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("links", "owner_id",
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
