"""
create links table

Revision ID: 5b0f1223ef6f
Revises: 
Create Date: 2026-05-06 18:43:02.474519

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "5b0f1223ef6f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
