"""
init links table

Revision ID: af8d9c6c20a0
Revises: 68d0850afd24
Create Date: 2026-05-07 16:37:49.441407

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af8d9c6c20a0"
down_revision: str | Sequence[str] | None = "68d0850afd24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("links",
    sa.Column("original_url", sa.String(), nullable=False),
    sa.Column("short_code", sa.String(length=16), nullable=False),
    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
    sa.PrimaryKeyConstraint("id", name=op.f("pk_links")),
    sa.UniqueConstraint("short_code", name=op.f("uq_links_short_code")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("links")
    # ### end Alembic commands ###
